### PR TITLE
Migrate to Bootstrap 3.1.1. Now it looks nice on mobile devices

### PR DESCRIPTION
**Pull request by gam6itko**
- bootstrap v3 instead v2
- minified js
- fixed unclosed html tags
- more flexible  twig layout  inheritance
- compatible with mobile devices

### CODE REVIEW

**Comment by cboden** [comment]
It always seems to display the mobile screen version even on desktop browsers. There's a bit of an issue with spacing an navigation header as well. 

screen shot 2015-01-13 at 7 22 22 pm

**Comment by gam6itko** [comment]
I'll fix it as soon as possible

**Comment by gam6itko** [comment]
How you had reached that bahvior ?
The site should look like this 

ed08b-clip-90kb

**Comment by gam6itko** [comment]
typo

**Comment by cboden** [comment]
I just pulled the branch and took a look at it. I checked with Safari and Chrome on OS X Yosemite.

**Comment by x-plora** [comment]
I've just tested on OSX Yosemite in Chrome and Safari. And it looks good.
image

image

**Pull request closed without merging**
