### PR TITLE
Correct a typo in `views/docs/{deploy, push}.html.twig`

### PR DESCRIPTION
**Pull request by Benjamin-Loison**

### CODE REVIEW

**Comment by SimonFrings** [comment]
Hey @Benjamin-Loison, thanks for finding these typos and submitting your changes :+1:

I don't think it is necessary to use two commits for this PR, I would suggest to combine them into one commit. To do so you have to:

1. Check out the pushed branch with your changes:

```
git checkout patch-1
```

2. Squash the two commits into one and give the new resulting commit a fitting message:

```
git reset --soft HEAD~2 &&  git commit --edit -m"Correct a typo in `views/docs/{deploy, push}.html.twig`"
```

3. Force push the new changes into your fork, make sure to replace `<remote | repository>` with your fork remote or repository in the following command  :

```
git push <remote | repository> patch-1 -f
```

I hope this helps :+1:

**Comment by Benjamin-Loison** [comment]
@SimonFrings I applied the requested modification.

**Review by SimonFrings — APPROVED** [review]
Nice :+1:

**Review by clue — APPROVED** [review]
@Benjamin-Loison Thanks for looking into this, keep it up! :shipit:

**Pull request merged**
